Fix optind undeclared error in utils.h
- Add #include <getopt.h> to utils.h
- This fixes the compilation error: 'optind' undeclared in reset_getopt()
- optind is used in the reset_getopt() function but getopt.h was not included

The error occurred because jpeg_utils.c includes utils.h which uses optind
but doesn't include the necessary header file for getopt functions.